### ISSUE TITLE
Bulk upload utility

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Classic#104]
While it is workable there is room for improvement. The following is creating issues regularly and it would be nice to have simple protection against those two following cases:

- The spreadsheet will often load many empty records. If there is no student data (like no first name and no last name then no record should be imported).

- Bad dates inevitably always slip in. Can a quick test be done on the dates columns for a valid yyyy-mm-dd format and refuse the students/staff with any bad date.

This will help tremendously.

**Comment by sarika0lal** [comment]
Hello,

We appreciate your observation and would like to inform that your suggestion has been implemented for the next release.

Thank you.

**Comment by sarika0lal** [comment]
We released a new version and the issue has been fixed there. Please check and let us know your feedback in case you have any.
