### ISSUE TITLE
Data Import Utility showing blank after uploading a file

### ISSUE THREAD

**Issue by OptimusSigh** [OS4ED/openSIS-Classic#144]
![blank](https://user-images.githubusercontent.com/25926803/96865992-94290980-1462-11eb-9ad9-734e8d52e971.png)

**Comment by EvanofMT** [comment]
I'm seeing the same issue on version 7.6.

**Comment by EvanofMT** [comment]
I'm using OpenSIS 7.6.

I turned on php error reporting on the DataImport.php file and found that the PHPExcel module is causing the error.  A few files within /modules/tools/Classes contain an invalid reference to "_null". PHP is throwing a fatal error when encountering this.

For example, on line 140 of "modules/tools/Classes/PHPExcel.php" you'll find:
 
$this->_workSheetCollection[$k] = _null; 

"=_null" should be changed to "= null" (without the underscore).

I checked the most recent version of PHPExcel ([https://github.com/PHPOffice/PHPExcel](https://github.com/PHPOffice/PHPExcel)) and it does not include the reference to "_null".  It includes the reference to "null" without the underscore.

Within OpenSIS 7.6, I found at least five files under "/modules/tools/Classes" that contain the invalid null reference.
I'm wondering if the module PHPExcel is too out of date for newer versions of PHP (I'm using 7.3).  The GitHub project for PHPExcel shows that this project was discontinued four years ago and replaced with a newer project.

**My SOLUTION TO GET PAST blank screen:**  download the "[Classes](https://github.com/PHPOffice/PHPExcel/tree/1.8/Classes)" directory from the PHPExcel Github page and replace it within OpenSIS.  

This gets me past the blank screen and shows the list of columns from my imported Excel file.  However, this reveals a new issue in that OpenSIS will not map the columns from my file to the valid columns used by OpenSIS database tables.

**Comment by EvanofMT** [comment]
Once I got the file upload working, I found that the Middle Name label (when matching upload columns to OpenSIS available columns) is labelled incorrectly as "First Name".  This is a typo in the DataImport.php file.

To fix, open DataImport.php in a code editor and modify lines 124 and 221.

FROM:
'MIDDLE_NAME' =>_firstName,

TO:
'MIDDLE_NAME' =>_middleName,

**Comment by sarika0lal** [comment]
We released a new version and the issue has been fixed there. Please check and let us know your feedback in case you have any.
