### ISSUE TITLE
Sesion is empty at install stage

### ISSUE THREAD

**Issue by jrichardsz** [OS4ED/openSIS-Classic#145]
In file **install/Ins2.php**

**$_SESSION** is empty and due to that db connection can not be established.

    $dbconn = new mysqli($_SESSION['server'], $_SESSION['username'], $_SESSION['password'], $_SESSION['db'], $_SESSION['port']);

But if I hardcode the values, everything works:

    $dbconn = new mysqli("192.168.1.60", "root", "secret", "opensis", 3306);

# Research

I printed $_SESSION in  with **install/Ins1.php**

    foreach ($_SESSION as $key=>$val)
    error_log($key." ".$val, 0);

And $_SESSION has the expected values. 

So what is happening **install/Ins2.php** ?

# Environment

- ubuntu 
- php 7.3 / php 7.4

# Redirect 

I think the redirect from step1 to step2 could be the reason. I had to use

    echo "<script type='text/javascript'> document.location = 'Step2.php'; </script>";

instead

    header('Location: Step2.php');

in **install/Ins1.php**, because, redirect was not working

**Comment by jrichardsz** [comment]
I fixed moving **session_start()** at the first line of several install files.

**Comment by openSISAdmin** [comment]
Richard, please download the openSIS ver 8.0 and try it out. If this still exists, do a fix and a pull request. Thanks

**Comment by jrichardsz** [comment]
I tried the last version and works fine.
Thanks
