### ISSUE TITLE
Error creating database on first setup

### ISSUE THREAD

**Issue by renegade9x** [OS4ED/openSIS-Classic#147]
Greetings, I have downloaded the opensis 7.3 and have tried running it on my linux mint laptop. I installed mysql 8 and i have this error showing up, when ii tries to create the database for the first time.

**_You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank NUMERIC; declare cur1 cursor for select mp.marking_period_id, ' at line 9_**

**Comment by kevin-soutar** [comment]
I have this issue as well, running bitami lampp on Gcloud.  It would be really great to see a fix for this problem.

**Comment by kevin-soutar** [comment]
[opensis forums post](https://sourceforge.net/p/opensis-ce/discussion/1110993/thread/fe8b3d1fe2/?limit=25#7231) Looks like the current "fix" is to just use an older version of mysql

**Comment by openSISAdmin** [comment]
Please try out openSIS ver 8.0. It should be fixed.

**Comment by soepai** [comment]
openSIS Installation

- Choose Package **[passed]**
- System Requirements **[passed]**
- Database Connection **[passed]**
- Database Selection **[created a new database]**

It is taking too long to create a new database; next steps did not come up. The web page doesn't respond, and I can't set up the below steps. When I refresh the page it starts with the beginning. 

- School Information 
- Site Admin Account Setup
- Ready to Go! 

Can I bypass these installation step with configuring the config files using CLI interface?

I'm using 
Apache 2.4.52
Mysql 8.0.39-0
Ubuntu 22.04.1
PHP 8.3.13
