### ISSUE TITLE
Redirecting to Blank blue screen on giving database Credentials.

### ISSUE THREAD

**Issue by likhith-ch** [OS4ED/openSIS-Classic#148]
While installing opensis in second step after giving credentials it is redirecting to blank blue screen.
I have tried max_execution_time and permissions to 777 but did not work.
I am trying to install it in cloud.
Can you help me solve this issue.

**Comment by danielrodrigotest** [comment]
Same here

**Comment by tmtns** [comment]
Same issue, Any update?

**Comment by likhith-ch** [comment]
No update

**Comment by EvanofMT** [comment]
Are you using the latest version, OpenSIS 7.6?

**Comment by likhith-ch** [comment]
Yes, I am!

**Comment by EvanofMT** [comment]
I think there is an error occurring when the OpenSIS installer is attempting to contact the database.  To makre sure I understand where the failure is happening, is the attached screenshot (the "Database Connection" step the last step you see before you get a blank blue screen?  (if different, please upload a screen shot of the last page you see before the blank blue screen)

![OpenSIS76-DBconnection-troubelshoot](https://user-images.githubusercontent.com/65497341/106625169-6c0e7380-6544-11eb-8e34-582f723df57b.png)

**Comment by EvanofMT** [comment]
I came across a similar description from another user.  I wonder if the PHP Mysqli module is **not** active on your cloud server.  If you have command line access to your cloud server, try the following commands:

1. Confirm the PHP Mysqli module is installed:
sudo phpenmod mysqli 

2. If the module wasn't installed before (but now is), then Restart the Apache service:
sudo service apache2 restart

3. Try the OpenSIS installation again.

**Comment by likhith-ch** [comment]
I tried enabling error message and PHP Mysqli module is also installed. But still I am getting the same issue.

**Comment by likhith-ch** [comment]
'Notice: Undefined index: upreq in /public_html/install/index.php on line 55 ' got this notice in install/index.php file

**Comment by EvanofMT** [comment]
The error on the install/index.php can be ignored.  That variable is used if an upgrade from an older OpenSIS version is needed.

I can't reproduce the error on my test server.  And I don't see anything in the installer files that would be causing the process to break.  The database connection form is generated by the file "install/Step1.php" and when submitted, it activates the file "install/Ins1.php".

What about your version of PHP; what version of PHP is your server running? (I'm using PHP 7.3)

**Comment by likhith-ch** [comment]
My PHP version is 7.3.27

**Comment by EvanofMT** [comment]
I encountered this problem on the "Site Admin Account Setup" step.  I wonder if the cause is similar.

I tried creating an OpenSIS user name that contained a space; something like "Anthony Ness" (space between the words).  When a username with a space is submitted, an error occurs but no error message.  The process attempts to go to the next step but it fails to load the remaining installation form and fails by showing only the blue screen.

When you are typing your database username and password, do either of those have a space within the names?

If you don't have a space in the username or password field, I wonder if there is a conflicting character in one of these.

**Comment by EvanofMT** [comment]
Also (other idea) are you using "localhost" as the server name?

**Comment by dr-gangrena** [comment]
Same problem here, using  XAMPP v3.2.4 and PHP 8.0.3

**Comment by openSISAdmin** [comment]
Try with Php 7.x

**Comment by openSISAdmin** [comment]
Use this version of xampp   https://www.apachefriends.org/blog/new_xampp_20210313.html

**Comment by dr-gangrena** [comment]
Thanks! i just came to tell the community my solution and found your kind response.
I was lucky with an older version of XAMPP and Maria DB server version 10.4
It works!

**Comment by openSISAdmin** [comment]
Glad it worked.

**Comment by subhobiswas** [comment]
you just have to pick the >5.6 and <8.1 php version in your webserver !!!

**Comment by openSISAdmin** [comment]
This issue is fixed. Try openSIS 8.0.
