### ISSUE TITLE
Sample Data install causing failure

### ISSUE THREAD

**Issue by EvanofMT** [OS4ED/openSIS-Classic#149]
I downloaded opensis7.6 this morning and on install, the installer will fail with a general server disconnect error IF school sample data install is selected.

It ran without errors a few weeks ago when I tried, but I was using an older download of opensis7.6.  Anyone seeing this issue on a fresh download of opensis7.6?

**Comment by intouch2019** [comment]
i am also facing same error

**Comment by EvanofMT** [comment]
I'm trying now with openSIS8.  I'm running openSIS on Raspbian 10 (Debian) with MariaDB 10.3.36.  I'm connecting to the installer setup from Firefox 108, Windows 11.

The sample data causes a failure.

OpenSIS 8 installs without error **without** the sample data .  However, with the sample data, the installation process stalls on the "Configuring database. Please wait..." for more than 10 minutes and then the browser connection resets and fails.  The browser window fails with the "The Connection was reset" error page.

I remember on an older version of opensis I had a problem with a MySQL command in the sample data that wasn't valid for MariaDB 10.  I'll look into it and see if I can find it.

**Comment by openSISAdmin** [comment]
Please use the latest code of openSIS 9.

Thanks

**Comment by EvanofMT** [comment]
Okay!  thank you.  I did not realize version 9 was out.  I'm excited to try it.

**Comment by EvanofMT** [comment]
I tried with version 9 on the same system noted above and the sample data installed quickly and without error.

Thank you!

**Comment by openSISAdmin** [comment]
Great. Happy to hear that.
