### ISSUE TITLE
Wrong array values on DataImport.php

### ISSUE THREAD

**Issue by EvanofMT** [OS4ED/openSIS-Classic#150]
![OpenSSI-Dataimport-AltID-screenshot](https://user-images.githubusercontent.com/65497341/106164034-908ada00-6157-11eb-8ed9-9e2d0dfad0ed.JPG)

Using OpenSIS 7.6.

When testing the Staff Import tool, I found that Alternate ID was missing from the "One to One relationship" list when matching uploaded columns to db columns.

File affected: /modules/tools/DataImport.php
LINES: 404 and 478

The the Alternate_ID key exists in the array, but the array value is incorrect.  The value is set to "_firstname" and should be "_alternateId"

Easy fix.

**Comment by EvanofMT** [comment]
Similar mistake for Middle Name (check both Student and Staff sections).  This example highlights the Staff section of the file.

File affected: /modules/tools/DataImport.php
LINES: 124, 220, 397, and 471

The the MIIDDLE_NAME key exists in the array, but the array value is incorrect.  The value is set to "_firstname" and should be "_middleName"

![OpenSSI-Dataimport-MiddleName-screenshot](https://user-images.githubusercontent.com/65497341/106164416-f1b2ad80-6157-11eb-8b67-d31539bc57ee.JPG)

**Comment by openSISAdmin** [comment]
This has been fixed.
