### ISSUE TITLE
Calendar no longer showing events

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Classic#157]
No events shown below.

![calendar-2](https://user-images.githubusercontent.com/1091769/108317286-02a38b80-71f9-11eb-8c61-90c6a0c116a1.jpg)

But when clicking on List Events above

![calendar-1](https://user-images.githubusercontent.com/1091769/108317320-0df6b700-71f9-11eb-8fd7-a293393772c3.jpg)

I am expecting to see the events listed with a link as before with the ability to open/edit.

Looking in the database the events are all there.

![calendar-3](https://user-images.githubusercontent.com/1091769/108317491-557d4300-71f9-11eb-8d85-4d69cd1ee773.jpg)

The version running is a recent merge of the master branch.

**Comment by openSISAdmin** [comment]
Could not replicate.
