### ISSUE TITLE
Left over include statement in many files?

### ISSUE THREAD

**Issue by EvanofMT** [OS4ED/openSIS-Classic#165]
I've noticed this include statement within many files under the modules directory:

include('../../RedirectModulesInc.php');

It's declared at the beginning of many files.  Two examples are: \modules\grades\DeletePromptX.fnc.php and \modules\grades\EditReportCardGrades.php

I don't see this file anywhere within OpenSIS 7.6.  Is this a left over line from a previous version?  I want to delete it if it is not needed.  It causes so many false errors when error reporting is turned on.

Any suggestions?

**Comment by openSISAdmin** [comment]
Will get you an answer from the Dev team. Thanks for reporting.

**Comment by openSISAdmin** [comment]
This has been cleaned up in ver 8.0. Please check.
