### ISSUE TITLE
ParamLibFnc.php issues prevent installation/configurattion

### ISSUE THREAD

**Issue by mbatchelor** [OS4ED/openSIS-Classic#172]
Brand-new environment, brand-new install.
PHP: 8.0.9
Version: 7.3
DB: MariaDB

Once you type in MySQL information, and click next, you see just a blue empty page. Debugging reveals a couple of issues with ParamLibFnc.php:
1- https://github.com/OS4ED/openSIS-Classic/blob/master/functions/ParamLibFnc.php#L207 - PARAM_ALPHANUMS should be quoted in line 207
2- https://github.com/OS4ED/openSIS-Classic/blob/master/functions/ParamLibFnc.php#L433 - PARAM_NAME is not defined
After fixing #1 above, I was able to go further in the install when I ran into #2.

For me, I added the following which let me continue the installation:
/**
 * PARAM_NAME - Remove everything no a-zA-Z/_-
 * /
define('PARAM_NAME', 0x1300);

That let me get to the step of defining the Site Administrator Account

Unfortunately, after this, it blew up in Warehouse.php on line 29:
Uncaught Error: Undefined constant "WAREHOUSE_PHP" in .../Warehouse.php:29

I suppose that's a different bug report.

**Comment by sarika0lal** [comment]
Hello,

We appreciate your observation and would like to inform that your suggestion has been implemented for the next release.

Thank you.

**Comment by sarika0lal** [comment]
We released a new version and the issue has been fixed there. Please check and let us know your feedback in case you have any.
