### ISSUE TITLE
Changing scores for activities does not work even on the demo

### ISSUE THREAD

**Issue by edanpedragosa** [OS4ED/openSIS-Classic#176]
Hi!  It seems that OpenSIS 8 does not seem to allow changing scores for each activities. Any reason for this?

**Comment by openSISAdmin** [comment]
We are unable to understand your concern. Can you provide a little more explanation of the issue?  Screen shots and even a short video (screen cast) will be very helpful.

Thanks

**Comment by edanpedragosa** [comment]
Okay, I've attached the video of what's happening when a user tries to change points/score of an activity on demo site.

https://user-images.githubusercontent.com/34432331/130162741-1e76b7e5-2faa-4734-9118-caf47ca05640.mp4

**Comment by edanpedragosa** [comment]
Checking on the console logs it shows UnCaught TypeError as in the attached image. It happens when you click the SAVE button.
![image](https://user-images.githubusercontent.com/34432331/130173450-06b014b7-e133-4ae7-b801-c39d74a9b895.png)

**Comment by openSISAdmin** [comment]
Please use the latest code and check it.

**Comment by edanpedragosa** [comment]
Thanks! Now confirmed working using the updated codes.
