### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [OS4ED/openSIS-Classic#184]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by jrichardsz** [comment]
I will appreaciate the security advice

**Comment by zidingz** [comment]
Hey @openSISAdmin, 

I've just filled out the form. I'm wondering if you can confirm its receipt, as I am met with this error whilst verifying my email. Thank you.

<img width="496" alt="Screenshot 2021-08-31 at 13 03 34" src="https://user-images.githubusercontent.com/28839565/131499245-278b9434-47c7-43a2-87f2-003763826685.png">

**Comment by openSISAdmin** [comment]
The link is: https://support.os4ed.com
