### ISSUE TITLE
Do I need to upgrade if there is no new release?

### ISSUE THREAD

**Issue by mpx14** [OS4ED/openSIS-Classic#186]
I ve been following the project here for some time and from my understanding it seems that upgrade is only necessary when their is a new release version. 

If I do I git pull in between to get the latest bug fixes etc before a new release do I also need to perform an upgrade or can I just drop the new code in line?

Thanks a lot in advance.

**Comment by openSISAdmin** [comment]
Well, if you just pull the code from git it will work for point releases like 7.3, 7.4, etc. However, since we had database changes, we released this as ver 8.0. For this release to work, you must upgrade.
