### ISSUE TITLE
Enrollment code options are duplicated

### ISSUE THREAD

**Issue by jrichardsz** [OS4ED/openSIS-Classic#187]
In the option:

Students >> enrollment info 

![image](https://user-images.githubusercontent.com/3322836/131411679-277d920e-b5fb-4192-9549-67c761d038e4.png)

The options: transferred if and rollover are duplicated

**Comment by openSISAdmin** [comment]
Under what circumstances are you getting double?

If you install the system it does not create double.

**Comment by jrichardsz** [comment]
I used the installation with demo sample

**Comment by openSISAdmin** [comment]
We are unable to replicate the issue.
