### ISSUE TITLE
Group Schedule don't work

### ISSUE THREAD

**Issue by jrichardsz** [OS4ED/openSIS-Classic#197]
I have two students. I added the same course to each student (one by one) and works

![gif](https://i.ibb.co/q1VQYL8/opensis-student-schedule.gif)

But If I try to add another course using the **Group Schedule** option, just loads some seconds and my students continue to have only one course:

![git](https://i.ibb.co/wS6qYj2/opensis-group-schedule.gif) 

I'm doing something wrong?

Thanks

**Comment by openSISAdmin** [comment]
We are unable to replicate the error. Group scheduling works fine in openSIS. You could be having an isolated issue.

**Comment by jrichardsz** [comment]
I found the issue:

- https://github.com/OS4ED/openSIS-Classic/blob/master/modules/scheduling/MassSchedule.php#L53

If I change this

```
echo "<script type='text/javascript'>";
echo "$('body').find('.jGrowl').attr('class', '').attr('id', '').hide();
    $.jGrowl("._scheduleStartDateCannotBeBeforeMarkingPeriodsEndDate.", {
        position: 'top-center',
        theme: 'alert-styled-left bg-danger',
        life: 5000,
    });";
echo "</script>";
```

for this

```
ShowErr(""._scheduleStartDateCannotBeBeforeMarkingPeriodsEndDate);
```
The violated rule appears:

![image](https://user-images.githubusercontent.com/3322836/132806400-09c8600c-c75b-4387-b029-ac116763a854.png)

Without this fix, just a page reload is showed without any message to the user.

In another way, thanks to the error message, I select a correct date and I was able to add this course to my two students. I received a green success message but in view schedule, just one course appear :(. If I try to add manually that course,I got this error:

![image](https://user-images.githubusercontent.com/3322836/132808060-3b6b70f3-5fe8-47be-8530-9b3ee8730b8b.png)

I thinks is something about my semester

![image](https://user-images.githubusercontent.com/3322836/132808168-5351054d-94df-4591-a933-73b2be9209b2.png)

or quarter

![image](https://user-images.githubusercontent.com/3322836/132808205-6e50270f-7c27-4386-9d43-f29454aacf31.png)

But at the moment of group schedule, mark period is not selectable

![image](https://user-images.githubusercontent.com/3322836/132808428-6ca5bd3e-8d26-4838-a55e-3f5197c4008e.png)

So, please, could you help to understand what is the relationship between : semester, quarter, marking period and group schedule?

Thanks for your time
