### ISSUE TITLE
How to add exams not related to semesters or quarters?

### ISSUE THREAD

**Issue by jrichardsz** [OS4ED/openSIS-Classic#200]
According to this https://support.os4ed.com/hc/en-us/articles/201209626-Input-Final-Grades the exams are related to marking periods: semesters and quarters

![image](https://user-images.githubusercontent.com/3322836/132976714-627a6ad3-4a98-4dfe-a557-d4e226c9d084.png)

- If I created 2 semesters with 2 quarters each one (without exam), teachers will have to enter the grades 7 times
2 semester + 4 quarters  + 1 final year
  - am I correct?
  
- Also if I use the checkbox [*] exam at marking period creation,  teachers will have to enter the grades 14 times?
  - ![image](https://user-images.githubusercontent.com/3322836/132976828-801aff6d-303e-4397-ae95-0f364a87f90a.png)
  - am I correct?

Final question: If teachers wants to take another kind of additional exams with its related grades, how can I add new exams?

Examples of exams not related to semesters or quarters ending:

- Middle exam
- Partial exam
- Laboratory exam

Thanks

**Comment by openSISAdmin** [comment]
Teachers can take exams as part of Gradebook grades and assign a percentage weightage to them.

Just like homework, classwork quiz, etc., have the teacher take the exam any time and assign a score and a percentage of the gradebook to it. It will show in the report card grade.
