### ISSUE TITLE
Error 7 in Upgrade.php

### ISSUE THREAD

**Issue by mpx14** [OS4ED/openSIS-Classic#201]
I am attempting to perform an upgrade from a production opensis 7.6 database to the latest version 8 code from github. After satisfying version 8 requirement to disable strict mode on the database the upgrade process begins but abruptly ends with a Blank page stating "Show Error 7".

Nothing else is visible in a way of an error message in any of the server's log files. 

Does anyone have more information as to how to navigate the conditions causing this error in Upgrade.php.

Thanks a lot in advance.

**Comment by openSISAdmin** [comment]
We are unable to replicate this. Please send us a video recording.
