### ISSUE TITLE
Suffix Label (lang)

### ISSUE THREAD

**Issue by Jbersot** [OS4ED/openSIS-Classic#206]
The lang definition _suffix is not use in /modules/students/includes/GeneralInfoInc.php 

lines 64 replace 'Suffix' by ''._suffix.''

replace 

if ($_REQUEST['student_id'] == 'new') {
    unset($_SESSION['students_order']);
    echo '<div class="well m-b-20 clearfix"><h6 class="m-t-0 text-success">'._studentName.'</h6><div class="row"><div class="col-lg-6"><div class="form-group">' . TextInput($student['FIRST_NAME'], 'students[FIRST_NAME]', ''._firstName.' *', 'size=12 class=form-control maxlength=50') . '</div></div><div class="col-lg-6"><div class="form-group">' . TextInput($student['MIDDLE_NAME'], 'students[MIDDLE_NAME]', ''._middleName.'', 'class=form-control maxlength=50') . '</div></div></div><div class="row"><div class="col-lg-6"><div class="form-group m-b-0">' . TextInput($student['LAST_NAME'], 'students[LAST_NAME]', ''._lastName.' *', 'size=12 class=form-control maxlength=50') . '</div></div><div class="col-lg-6"><div class="form-group m-b-0">' . SelectInput($student['NAME_SUFFIX'], 'students[NAME_SUFFIX]', 'Suffix', array('Jr.' => 'Jr.', 'Sr.' => 'Sr.', 'II' => 'II', 'III' => 'III', 'IV' => 'IV', 'V' => 'V'), '', '') . '</div></div></div></div>';

by 

if ($_REQUEST['student_id'] == 'new') {
    unset($_SESSION['students_order']);
    echo '<div class="well m-b-20 clearfix"><h6 class="m-t-0 text-success">'._studentName.'</h6><div class="row"><div class="col-lg-6"><div class="form-group">' . TextInput($student['FIRST_NAME'], 'students[FIRST_NAME]', ''._firstName.' *', 'size=12 class=form-control maxlength=50') . '</div></div><div class="col-lg-6"><div class="form-group">' . TextInput($student['MIDDLE_NAME'], 'students[MIDDLE_NAME]', ''._middleName.'', 'class=form-control maxlength=50') . '</div></div></div><div class="row"><div class="col-lg-6"><div class="form-group m-b-0">' . TextInput($student['LAST_NAME'], 'students[LAST_NAME]', ''._lastName.' *', 'size=12 class=form-control maxlength=50') . '</div></div><div class="col-lg-6"><div class="form-group m-b-0">' . SelectInput($student['NAME_SUFFIX'], 'students[NAME_SUFFIX]', ''._suffix.'', array('Jr.' => 'Jr.', 'Sr.' => 'Sr.', 'II' => 'II', 'III' => 'III', 'IV' => 'IV', 'V' => 'V'), '', '') . '</div></div></div></div>';

**Comment by sayan-os4ed** [comment]
Hello,

This issue is being worked on and will be fixed in the next release.

Thanks!

**Comment by sarika0lal** [comment]
We released a new version and the issue has been fixed there. Please check and let us know your feedback in case you have any.
