### ISSUE TITLE
Scheduling courses with "Custom Date Range"

### ISSUE THREAD

**Issue by jbbelton-code** [OS4ED/openSIS-Classic#209]
Hi,
I am attempting to create a course offering with a custom date range. The course can be created but when attempting
to add a student to the course or a group schedule, the course does not appear for scheduling. In the course
catalog the course does not appear with a marking period so it does not appear for selection in scheduling. This 
seems to be an error with custom date ranges as the course does not record a marking period. Any suggestions
or has anyone used custom date ranges? Thank you

James

**Comment by sarika0lal** [comment]
Hello,

We appreciate your observation and would like to inform that your suggestion has been implemented for the next release.

Thank you.

**Comment by sarika0lal** [comment]
We released a new version and the issue has been fixed there. Please check and let us know your feedback in case you have any.
