### ISSUE TITLE
Data Import Utility

### ISSUE THREAD

**Issue by klmartinson17** [OS4ED/openSIS-Classic#212]
1. On the Upload page, it would be good to say that the first row of the .XLS file must contain the field names.
2. The field names in the first row MUST NOT have a space within the name, OR at the end of the name. ie. "Bus Number" is not valid, and "BUS " is also not valid. Currently, they must be changed to "Bus_Number" and "BUS" in order to import. This should be changed.
3. XLSX file in the "Excel 2007-365" format of LibreOffice does not import. This should either be fixed, or excluded from the "Upload page" list of valid files.

**Comment by sayan-os4ed** [comment]
Hello,

This issue is being worked on and will be fixed in the next release.

Thanks!

**Comment by sarika0lal** [comment]
We released a new version and the issue has been fixed there. Please check and let us know your feedback in case you have any.
