### ISSUE TITLE
Student Info display

### ISSUE THREAD

**Issue by klmartinson17** [OS4ED/openSIS-Classic#214]
If one lists over 50 students, then 1-50 will be shown on page 1, and the 51-100 on page 2, etc. 
The "Section" part of the listing is correct on page 1. Not on page 2, rather it shows the section_id instead of section_id.name
If one goes back to page 1, section_id is shown, which is not correct.

**Comment by sayan-os4ed** [comment]
Hello,

This issue is being worked on and will be fixed in the next release.

Thanks!

**Comment by sarika0lal** [comment]
We released a new version and the issue has been fixed there. Please check and let us know your feedback in case you have any.
