### ISSUE TITLE
Portal Notes only show page 2

### ISSUE THREAD

**Issue by track1riley** [OS4ED/openSIS-Classic#215]
Once you have enough portal notes that require you to go to page 2 to enter new notes, it resets all notes from page 1 of visible to: to not visible.

**Comment by sayan-os4ed** [comment]
Hello,

This issue is being worked on and will be fixed in the next release.

Thanks!

**Comment by sarika0lal** [comment]
We released a new version and the issue has been fixed there. Please check and let us know your feedback in case you have any.
