### ISSUE TITLE
Installer not working with Mysql 8 due new keyword "rank"

### ISSUE THREAD

**Issue by bschuele** [OS4ED/openSIS-Classic#218]
In Msql, starting with 8.0.2, there is a new keyword "rank". https://dev.mysql.com/doc/refman/8.0/en/keywords.html
Rank is used in /install/OpensisProcsMysqlInc.sql and /install/OpensisUpdateProcsMysql.sql as a variable, and this leads to a syntax error.

**Comment by sayan-os4ed** [comment]
Hello,

This issue is being worked on and will be fixed in the next release.

Thanks!

**Comment by klmartinson17** [comment]
It is the PHP version that needs to go from 7.4 to 8.x.  NOT the MySQL version (5.7)
This is required so that website vulnerability tests can pass.

**Comment by klmartinson17** [comment]
My experience has been that:
This works:               Apache 2.4.52, MariaDB 10.4.22, PHP 7.4.27,
This does not work: Apache 2.4.52, MariaDB 10.4.22, PHP 8.0.15

**Comment by sarika0lal** [comment]
Hello,

We appreciate your observation and would like to inform that your suggestion has been implemented for the next release.

Thank you.

**Comment by sarika0lal** [comment]
We released a new version and the issue has been fixed there. Please check and let us know your feedback in case you have any.
