### ISSUE TITLE
Security Advisory for OpenSIS

### ISSUE THREAD

**Issue by PearlTechSecurity** [OS4ED/openSIS-Classic#220]
Greetings,

The Pearl Technology Security Operations group has found security vulnerabilities impacting OpenSIS. Due to the nature of the security issues, please mark this issue as private and/or provide an e-mail addresses to receive advisory reports. 

We ask that all further correspondence regarding this issue CC the following e-mail address: securityresearch at pearltechnology dot com

**Comment by PearlTechSecurity** [comment]
Greetings, 

We have not received any communication regarding the vulnerabilities found in OpenSIS.

Please note, Pearl Technology Security Operations will disclose the vulnerabilities after 90 days after initial contact if no communication has been established. 

Thanks

**Comment by PearlTechSecurity** [comment]
Greetings, 

We have still not received any communications regarding vulnerabilities found in OpenSIS. This will be our final attempt. 

Pearl Technology Security Operations will publicly disclose these vulnerabilities and associated CVEs after 90 days of no response. 

Thanks

**Comment by openSISAdmin** [comment]
Did you email the specific issues to info@os4ed.com?  We need them with methods of recreation.

Thanks
