### ISSUE TITLE
Group Schedule Error

### ISSUE THREAD

**Issue by Imhotep758** [OS4ED/openSIS-Classic#222]
![2022-01-17](https://user-images.githubusercontent.com/97898427/149807907-653e1f6a-4373-4a24-a851-b5a6b19e5e1e.png)

Getting this DB execute failure error every time I group schedule students. Does anyone has a solution to solve this issue

**Comment by sarika0lal** [comment]
Hello,

Apologies for the issue encountered by you. 

We keep updating our code. So, in order to solve the issue, we suggest you to re-install/upgrade the product. We hope you won't have to face the issue again.

Thank you.
