### ISSUE TITLE
Student's Home Address

### ISSUE THREAD

**Issue by klmartinson17** [OS4ED/openSIS-Classic#224]
Students --> Add a Student -tab-to- Addresses & Contacts
"Address Line 1" can have one space between words. Two spaces between words causes the error "Please enter address".
It would be better to accept multiple spaces, or reduced multiple spaces to 1 space character.

**Comment by sarika0lal** [comment]
Hello,

We appreciate your observation and would like to inform that the issue has been resolved. Please check and let us know your feedback in case you have any.

Thank you.
