### ISSUE TITLE
Default Date is Central European Time zone

### ISSUE THREAD

**Issue by klmartinson17** [OS4ED/openSIS-Classic#226]
![Screenshot 2022-02-09 160500](https://user-images.githubusercontent.com/94560041/153305736-101e73d5-0113-4e6f-bd90-fd925df9e5b2.png)
At 16:00 Feb. 9 2022 Mountain Time zone in Alberta, the Default Date switched to Feb. 10. That means OpenSIS must be running on Central European Time zone.

**Comment by openSISAdmin** [comment]
openSIS uses server time. You can change the server time to your local time.
