### ISSUE TITLE
Table headings could be more descriptive. See Schedule Report

### ISSUE THREAD

**Issue by klmartinson17** [OS4ED/openSIS-Classic#230]
![Screenshot 2022-02-11 084742](https://user-images.githubusercontent.com/94560041/153623359-85d3ab3c-c2c2-4c85-be41-9a6a5eff6e57.png)
![Screenshot 2022-02-11 084851](https://user-images.githubusercontent.com/94560041/153623374-823b8ca5-e98d-4239-b2f5-2582f3e54e9f.png)

**Comment by klmartinson17** [comment]
![Screenshot 2022-02-11 101500](https://user-images.githubusercontent.com/94560041/153637579-d88d9b00-6f52-418f-b0f9-1a11d226a72b.png)

**Comment by manasdas272** [comment]
Hello,

We appreciate your observation and would like to inform that your suggestion has been implemented. Please check and let us know your feedback in case you have any.

Thank you.
