### ISSUE TITLE
Staff Info. Sort by Period, not by Course.

### ISSUE THREAD

**Issue by klmartinson17** [OS4ED/openSIS-Classic#232]
It would be nice if Users --> Staff --> Staff Info --> Schedule
was sorted by Period, and not by Course.

![Screenshot 2022-02-11 103530](https://user-images.githubusercontent.com/94560041/153640812-39b99d91-ad54-4b64-a019-ae400e89916c.png)

**Comment by openSISAdmin** [comment]
Agreed

**Comment by klmartinson17** [comment]
Sorting by Time would be even better.

**Comment by manasdas272** [comment]
Hello,

We appreciate your observation and would like to inform that your suggestion has been implemented. Please check and let us know your feedback in case you have any.

Thank you.
