### ISSUE TITLE
Sort of a "student selection" results in ALL students listed.

### ISSUE THREAD

**Issue by klmartinson17** [OS4ED/openSIS-Classic#233]
Select only students in one course.
![Screenshot 2022-02-11 155739](https://user-images.githubusercontent.com/94560041/153682255-3cdd5ee0-82eb-4ce3-9c2e-1cd2cea062a5.png)

Sort based upon one of the column headers.
![Screenshot 2022-02-11 155909](https://user-images.githubusercontent.com/94560041/153682260-bda0c650-5ccc-4b07-b6dd-f284ffc9662f.png)

The result shows ALL students.
![Screenshot 2022-02-11 155959](https://user-images.githubusercontent.com/94560041/153682264-8e8f8135-45e4-474e-9f11-0790126af5b3.png)

Either disable the column sort, or sort on the "student selection".

**Comment by manasdas272** [comment]
Hello,

We appreciate your observation and would like to inform that your suggestion has been implemented. Please check and let us know your feedback in case you have any.

Thank you.
