### ISSUE TITLE
Student name could be displayed

### ISSUE THREAD

**Issue by klmartinson17** [OS4ED/openSIS-Classic#235]
In Scheduling --> Student Schedule one Selects a Section (homeroom)
![Screenshot 2022-02-16 100336](https://user-images.githubusercontent.com/94560041/154318497-ca7b7ebc-fc6d-4f78-b2e5-bed8bd42e6fa.png)
Then select one student.

The result is that you view the Student's schedule:
![Screenshot 2022-02-16 100411](https://user-images.githubusercontent.com/94560041/154318569-5a17ce42-5484-449b-b66e-ca84bed34529.png)

If you want to change anything about the student's schedule, you click "Student Schedule", and the student's name is no longer displayed. It would be good to display the Student's name so that you know which student's schedule you are changing.
![Screenshot 2022-02-16 100703](https://user-images.githubusercontent.com/94560041/154318818-d4a499ea-b037-4a55-8a43-678e0ae7223e.png)

**Comment by sarika0lal** [comment]
Hello,

We appreciate your observation and would like to inform that your suggestion has been implemented. Please check and let us know your feedback in case you have any.

Thank you.
