### ISSUE TITLE
Group Delete wording

### ISSUE THREAD

**Issue by klmartinson** [OS4ED/openSIS-Classic#240]
Some text changes for the Group Delete function.

![Capture5](https://user-images.githubusercontent.com/8726603/156200320-823e55ff-4548-45d3-9ca5-abd6c2c50c0b.PNG)

![Capture2](https://user-images.githubusercontent.com/8726603/156198904-00de8e00-0e7f-41c5-8b5c-28e2b580a34a.PNG)
![Capture1](https://user-images.githubusercontent.com/8726603/156198988-cc9ea5f5-58d0-4e79-9326-f638ce80cc56.PNG)
![Capture3](https://user-images.githubusercontent.com/8726603/156199008-40bb1ad9-15ad-48ee-9d6b-91ad9e5655c5.PNG)
![Capture4](https://user-images.githubusercontent.com/8726603/156199030-16854127-6235-482b-9598-2bb225209a50.PNG)

**Comment by sarika0lal** [comment]
Hello,

We didn't face this issue in our system. Please try to use our latest code and let us know your feedback on the same.

Thank you.
