### ISSUE TITLE
Remove attendance record.

### ISSUE THREAD

**Issue by klmartinson** [OS4ED/openSIS-Classic#242]
Examples of how one can delete one student for one class on one date:

Delete from attendance_period where school_date=’2022-02-01’ and period_id=6 and updated_by=13 and student_id=195;

Example of how to delete all students in one class on one date.
Delete from attendance_period where school_date=’2022-02-01’ and period_id=6 and updated_by=13;
Delete from attendance_completed where school_date=’2022-02-01’ and period_id=6 and staff_id=13;

![Capture7](https://user-images.githubusercontent.com/8726603/156205244-5e78c01e-fd25-4704-9666-2a67553ba972.PNG)

**Comment by openSISAdmin** [comment]
You can work on this on your build.
