### ISSUE TITLE
Attendance --> Add Absenses issue with "select students by Course"

### ISSUE THREAD

**Issue by klmartinson** [OS4ED/openSIS-Classic#243]
![Capture8a](https://user-images.githubusercontent.com/8726603/156215441-87083fd3-700d-45c7-981e-8a35d4591ff4.PNG)

![Capture8b](https://user-images.githubusercontent.com/8726603/156215456-01bf240b-bd60-4b4b-acce-8b23be55c835.PNG)

![Capture9](https://user-images.githubusercontent.com/8726603/156215468-7e2cc856-cb4f-45ae-b468-1c884a6c369a.PNG)

**Comment by openSISAdmin** [comment]
Add Absence is for an admin to add absence or other attendance code for a future date.

Use the attendance administration to override past attendances.
