### ISSUE TITLE
User --> Staff editing. required field error message

### ISSUE THREAD

**Issue by klmartinson17** [OS4ED/openSIS-Classic#252]
The error message says: Please select the joining date's month
It should read: Please select the joining day

![Screenshot 2022-03-09 131624](https://user-images.githubusercontent.com/94560041/157527730-9d5dd974-8146-4c26-8fad-cef50115f365.png)

**Comment by openSISAdmin** [comment]
The label is correct.

**Comment by sarika0lal** [comment]
Hello,

We appreciate your observation and would like to inform that your suggestion has been implemented. Please check and let us know your feedback in case you have any.

Thank you.
