### ISSUE TITLE
Data Import error message mismatch

### ISSUE THREAD

**Issue by klmartinson17** [OS4ED/openSIS-Classic#253]
The error message should be re-worded.

![Screenshot 2022-03-09 132519](https://user-images.githubusercontent.com/94560041/157531452-438d527a-ed72-40cc-9a82-e77847343bb0.png)

**Comment by openSISAdmin** [comment]
The right column is the database field. You choose what to map.

**Comment by klmartinson17** [comment]
openSISAdmin doesn't understand the issue. 
The issue is that the error message is not clear.  See the TEXT that I added to the jpg above.

**Comment by sarika0lal** [comment]
Hello,

We appreciate your observation and would like to inform that your suggestion has been implemented for the next release.

Thank you.
