### ISSUE TITLE
Access Denied. Student login attempt.

### ISSUE THREAD

**Issue by klmartinson17** [OS4ED/openSIS-Classic#255]
The Data Import tool can import Student usernames and passwords.
Logging in, I get "Access Denied" when trying to login as a Student.
Am not sure why.

![Screenshot 2022-03-10 104309](https://user-images.githubusercontent.com/94560041/157723411-067cf9b4-cf4e-4594-aad5-c95c81a631a0.png)

**Comment by sarika0lal** [comment]
Hello,

We appreciate your observation and would like to inform that your suggestion has been implemented for the next release.

Thank you.

**Comment by openSISAdmin** [comment]
This is because the password field is encrypted. When you upload the password via the Excel sheet it is going in plain text. We need the ability to encrypt and insert it.

**Comment by klmartinson17** [comment]
Maybe. Maybe not.
Another use case is:
a wired connection to apache works, and opensis login works.
A wireless connection to apache works, and opensis login gives "access
denied" ?

**Comment by openSISAdmin** [comment]
> I managed to fix the Access Denied by adding this line to index.php at line 535 $_SESSION['USERNAME']=$student_RET[1]['USERNAME'];
> 
> Is there any more development of OpenSIS here ? I am not seeing any activity in a while.

We released a new version today.
