### ISSUE TITLE
Student Info XLS download, Section Number

### ISSUE THREAD

**Issue by klmartinson17** [OS4ED/openSIS-Classic#256]
Something for me to add to the OSS.

![Screenshot 2022-03-16 091050](https://user-images.githubusercontent.com/94560041/158623832-a2cd623b-2b9c-4026-87ba-d1b60be8a631.png)

**Comment by klmartinson17** [comment]
![Screenshot 2022-03-16 150726](https://user-images.githubusercontent.com/94560041/158691211-bf22b6e6-2ee8-4a4b-8d9a-75986eaa809e.png)

**Comment by sarika0lal** [comment]
Hello,

We appreciate your observation and would like to inform that your suggestion has been implemented. Please check and let us know your feedback in case you have any.

Thank you.
