### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by Cr4ckC4t** [OS4ED/openSIS-Classic#270]
Several security issues have been identified in the latest release and were reported to [info@os4ed.com](mailto:info@os4ed.com) without a response yet. If time permits, could you have a look at the security report?

**Comment by openSISAdmin** [comment]
All security items reported are already fixed and will be released along with the net release within 2-3 weeks.

**Comment by openSISAdmin** [comment]
> Several security issues have been identified in the latest release and were reported to [info@os4ed.com](mailto:info@os4ed.com) without a response yet. If time permits, could you have a look at the security report?

![image](https://user-images.githubusercontent.com/7434280/208507943-2c8e6272-0de2-4b84-8b4e-84e92bb1ad32.png)
