### ISSUE TITLE
New Course Fixed Schedule 9.0 (no days)

### ISSUE THREAD

**Issue by track1riley** [OS4ED/openSIS-Classic#274]
No ability to choose the days when using a fixed schedule.  There is only a checkbox and no days.
![NoDays](https://user-images.githubusercontent.com/62354078/210613183-0564cf76-c711-44d6-bf54-7b213301bba4.png)

**Comment by openSISAdmin** [comment]
We are not able to replicate the issue. Could be your environment. This is what we get on Ubuntu machines running PHP 8.1 and latest Maria DB.

![image](https://user-images.githubusercontent.com/7434280/210623915-b5bf4f31-e68b-4332-9659-2bdf0e0a79e7.png)

**Comment by openSISAdmin** [comment]
@track1riley 

You can purchase support by the hours from os4ed.com and give us access to your server. This seems like an environment setup issue.

**Comment by track1riley** [comment]
It has something to do with the calendar and when it was created.  When I create a new calendar and use it, days appear.  I tried editing the old calendar and days do not appear.

**Comment by track1riley** [comment]
Not an issue.  It was when the calendar was set-up and no days were selected.
