### ISSUE TITLE
Automatic Installer

### ISSUE THREAD

**Issue by jcarney2024** [OS4ED/openSIS-Classic#276]
Hello Again, 
I had opened #265 a while ago, and it seems that this issue still isn't solved. When starting a fresh installation, the automatic installer page "Database Connection" seems to go blank.
![Blank Screen](https://i.ibb.co/c3QKN1s/Screenshot-2023-01-15-at-7-33-59-PM.png)

I'm getting a couple errors in my console.
`TypeError: null is not an object (evaluating 'document.getElementById('mainIframe').contentWindow') index.php:13`

`Failed to load resource: the server responded with a status of 500 (Internal Server Error) ./install/Step1.php`

**Comment by openSISAdmin** [comment]
Please follow this setup configuration of server.

https://github.com/OS4ED/openSIS-Classic/blob/master/docs/Steps%20to%20configure%20Ubuntu%20server%20for%20openSIS%20version%209.pdf

**Comment by jcarney2024** [comment]
Hi there, 
I seem to have changed directory permissions for the page file. I have reverted them back, and it seems to be working fine, however that first error is still appearing in the console on page load.

> `TypeError: null is not an object (evaluating 'document.getElementById('mainIframe').contentWindow') index.php:13`

**Comment by sarika0lal** [comment]
Hello,

We have updated the code with the fix. Please install our system using the fresh code and let us know your feedback in case you have any.

Thanks!
