### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by TsarSecurity** [OS4ED/openSIS-Classic#286]
Hi, i reported a vulnerability a while ago which seems to be fixed in https://github.com/OS4ED/openSIS-Classic/commit/3293f6115c4b24fd342bec120c8eb44846ad045c. Could you maybe close this issue on https://huntr.dev so it can have a CVE assigned? I have more vulnerabilities to report but i can't because this one is still open.

Thanks!

**Comment by sayan-os4ed** [comment]
Hello,

We have fixed the issues in the latest version. Please use the same and we hope that you won't see the issue again.

Thanks!
