### ISSUE TITLE
Teacher's start date cannot be after course period's start date.

### ISSUE THREAD

**Issue by fcortesjp** [OS4ED/openSIS-Classic#287]
version 7.4. 
Issue:
When I go to the course manager > course period in question, I see that eventhough the course period exist, it doesn't have anything under Choose Schedule Type (the course period was rolled over from a previous year), If I try to add a room, day and period when there's no teacher conflict I get an error that reads: "Teacher's start date cannot be after course period's start date."
the odd thing is that the teacher that I'm assiging to the course period has a start date prior the creation of the course period, because I did try to delete the rolled over course period and create a new one in hope to avoid the error. In any case the error persisted though.
if this is a bug in 7.4 ? and if so.. is it already addressed on a more recent version?
thanks.

**Comment by poulami12** [comment]
It's fixed in the latest version.
Thank You,

**Comment by fcortesjp** [comment]
Thank you @poulami12 I updated to latest version hopefully my users won't report this issue this year
cheers.
